[package]
name = "godot_json_schema"
version = "0.1.0"
authors = ["Houtamelo"]
edition = "2021"
readme = "README.md"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
godot = { package = "godot", git = "https://github.com/clementine-tech/gdext.git", features = ["experimental-threads", "experimental-godot-api"] }
serde = { version = "1.0", features = ["derive", "std"] }
serde_json = "1.0"
anyhow = "1.0"
declarative_type_state = "0.5.0"
itertools = "0.13.0"
clm = { package = "clm", git = "https://github.com/clementine-tech/clm.git", branch = "sweetdreams", optional = true }

# Do not update to 0.24, it has bugs that stop this crate from working.
jsonschema = { version = "=0.23", features = ["draft202012"] }

# Override gdext dependency of `clm`
[patch.crates-io]
godot = { git = "https://github.com/clementine-tech/gdext" }


[features]
default = []
integration_tests = ["clm"]

# Add the Documentation in README.md to the crate root.
[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
